export const ghostwriter = {
    "1": ["GeminiAPI", "Determine the most suitable genre and target audience for a story based on the following concept: {initialPrompt}"],
    "2": ["MobleysoftMASCOM", "Process genre and target audience data: {previousOutput}"],
    "3": ["GeminiAPI", "Synthesize a comprehensive world-building bible from the provided inputs: {initialPrompt} {uploadedImages} {genre} {targetAudience}"],
    "4": ["MobleysoftMASCOM", "Process world-building bible: {previousOutput}"],
    "5": ["GeminiAPI", "Analyze and refine the world-building bible: {previousOutput}"],
    "6": ["MobleysoftMASCOM", "Process refined world-building bible: {previousOutput}"],
    "7": ["GeminiAPI", "Develop a cast of compelling characters: {previousOutput}"],
    "8": ["MobleysoftMASCOM", "Process character details: {previousOutput}"],
    "9": ["GeminiAPI", "Create detailed backstories, motivations, and relationships for each character: {previousOutput}"],
    "10": ["MobleysoftMASCOM", "Process character backstories: {previousOutput}"],
    "11": ["GeminiAPI", "Expand on the settings described in the world-building bible: {previousOutput}"],
    "12": ["MobleysoftMASCOM", "Process expanded settings: {previousOutput}"],
    "13": ["GeminiAPI", "Consider cultural nuances, historical significance, and potential conflicts associated with each setting: {previousOutput}"],
    "14": ["MobleysoftMASCOM", "Process enhanced settings: {previousOutput}"],
    "15": ["GeminiAPI", "Brainstorm and create a detailed outline for a 16-chapter novel: {previousOutput}"],
    "16": ["MobleysoftMASCOM", "Process book outline: {previousOutput}"],
    "17": ["GeminiAPI", "Refine the 16-chapter book outline: {previousOutput}"],
    "18": ["MobleysoftMASCOM", "Process refined book outline: {previousOutput}"],
    "19": ["GeminiAPI", "Identify and explore the central themes and messages: {previousOutput}"],
    "20": ["MobleysoftMASCOM", "Process themes and messages: {previousOutput}"],
    "21": ["GeminiAPI", "Introduce compelling conflicts and challenges: {previousOutput}"],
    "22": ["MobleysoftMASCOM", "Process conflicts and challenges: {previousOutput}"],
    "23": ["GeminiAPI", "Strategically plan the pacing of the story: {previousOutput}"],
    "24": ["MobleysoftMASCOM", "Process story pacing: {previousOutput}"],
    "25": ["GeminiAPI", "Develop detailed outlines for each of the 16 chapters: {previousOutput}"],
    "26": ["MobleysoftMASCOM", "Process chapter outlines: {previousOutput}"],
    "27": ["GeminiAPI", "Review and enhance the 16 chapter outlines: {previousOutput}"],
    "28": ["MobleysoftMASCOM", "Process enhanced chapter outlines: {previousOutput}"],
    "29": ["GeminiAPI", "Generate front matter (title page, copyright, dedication): {previousOutput}"],
    "30": ["MobleysoftMASCOM", "Add front matter to the book: {previousOutput}"],
    "31": ["ClaudeAPI", "Write captivating chapter 1: {previousOutput}"],
    "32": ["MobleysoftMASCOM", "Process chapter 1 text: {previousOutput}"],
    "33": ["ChatGPTAPI", "Generate stunning images for chapter 1: {previousOutput}"],
    "34": ["MobleysoftMASCOM", "Add chapter 1 and images to the book: {previousOutput}"],
    "35": ["ClaudeAPI", "Write captivating chapter 2: {previousOutput}"],
    "36": ["MobleysoftMASCOM", "Process chapter 2 text: {previousOutput}"],
    "37": ["ChatGPTAPI", "Generate stunning images for chapter 2: {previousOutput}"],
    "38": ["MobleysoftMASCOM", "Add chapter 2 and images to the book: {previousOutput}"],
    "39": ["ClaudeAPI", "Write captivating chapter 3: {previousOutput}"],
    "40": ["MobleysoftMASCOM", "Process chapter 3 text: {previousOutput}"],
    "41": ["ChatGPTAPI", "Generate stunning images for chapter 3: {previousOutput}"],
    "42": ["MobleysoftMASCOM", "Add chapter 3 and images to the book: {previousOutput}"],
    "43": ["ClaudeAPI", "Write captivating chapter 4: {previousOutput}"],
    "44": ["MobleysoftMASCOM", "Process chapter 4 text: {previousOutput}"],
    "45": ["ChatGPTAPI", "Generate stunning images for chapter 4: {previousOutput}"],
    "46": ["MobleysoftMASCOM", "Add chapter 4 and images to the book: {previousOutput}"],
    "47": ["ClaudeAPI", "Write captivating chapter 5: {previousOutput}"],
    "48": ["MobleysoftMASCOM", "Process chapter 5 text: {previousOutput}"],
    "49": ["ChatGPTAPI", "Generate stunning images for chapter 5: {previousOutput}"],
    "50": ["MobleysoftMASCOM", "Add chapter 5 and images to the book: {previousOutput}"],
    "51": ["ClaudeAPI", "Write captivating chapter 6: {previousOutput}"],
    "52": ["MobleysoftMASCOM", "Process chapter 6 text: {previousOutput}"],
    "53": ["ChatGPTAPI", "Generate stunning images for chapter 6: {previousOutput}"],
    "54": ["MobleysoftMASCOM", "Add chapter 6 and images to the book: {previousOutput}"],
    "55": ["ClaudeAPI", "Write captivating chapter 7: {previousOutput}"],
    "56": ["MobleysoftMASCOM", "Process chapter 7 text: {previousOutput}"],
    "57": ["ChatGPTAPI", "Generate stunning images for chapter 7: {previousOutput}"],
    "58": ["MobleysoftMASCOM", "Add chapter 7 and images to the book: {previousOutput}"],
    "59": ["ClaudeAPI", "Write captivating chapter 8: {previousOutput}"],
    "60": ["MobleysoftMASCOM", "Process chapter 8 text: {previousOutput}"],
    "61": ["ChatGPTAPI", "Generate stunning images for chapter 8: {previousOutput}"],
    "62": ["MobleysoftMASCOM", "Add chapter 8 and images to the book: {previousOutput}"],
    "63": ["ClaudeAPI", "Write captivating chapter 9: {previousOutput}"],
    "64": ["MobleysoftMASCOM", "Process chapter 9 text: {previousOutput}"],
    "65": ["ChatGPTAPI", "Generate stunning images for chapter 9: {previousOutput}"],
    "66": ["MobleysoftMASCOM", "Add chapter 9 and images to the book: {previousOutput}"],
    "67": ["ClaudeAPI", "Write captivating chapter 10: {previousOutput}"],
    "68": ["MobleysoftMASCOM", "Process chapter 10 text: {previousOutput}"],
    "69": ["ChatGPTAPI", "Generate stunning images for chapter 10: {previousOutput}"],
    "70": ["MobleysoftMASCOM", "Add chapter 10 and images to the book: {previousOutput}"],
    "71": ["ClaudeAPI", "Write captivating chapter 11: {previousOutput}"],
    "72": ["MobleysoftMASCOM", "Process chapter 11 text: {previousOutput}"],
    "73": ["ChatGPTAPI", "Generate stunning images for chapter 11: {previousOutput}"],
    "74": ["MobleysoftMASCOM", "Add chapter 11 and images to the book: {previousOutput}"],
    "75": ["ClaudeAPI", "Write captivating chapter 12: {previousOutput}"],
    "76": ["MobleysoftMASCOM", "Process chapter 12 text: {previousOutput}"],
    "77": ["ChatGPTAPI", "Generate stunning images for chapter 12: {previousOutput}"],
    "78": ["MobleysoftMASCOM", "Add chapter 12 and images to the book: {previousOutput}"],
    "79": ["ClaudeAPI", "Write captivating chapter 13: {previousOutput}"],
    "80": ["MobleysoftMASCOM", "Process chapter 13 text: {previousOutput}"],
    "81": ["ChatGPTAPI", "Generate stunning images for chapter 13: {previousOutput}"],
    "82": ["MobleysoftMASCOM", "Add chapter 13 and images to the book: {previousOutput}"],
    "83": ["ClaudeAPI", "Write captivating chapter 14: {previousOutput}"],
    "84": ["MobleysoftMASCOM", "Process chapter 14 text: {previousOutput}"],
    "85": ["ChatGPTAPI", "Generate stunning images for chapter 14: {previousOutput}"],
    "86": ["MobleysoftMASCOM", "Add chapter 14 and images to the book: {previousOutput}"],
    "87": ["ClaudeAPI", "Write captivating chapter 15: {previousOutput}"],
    "88": ["MobleysoftMASCOM", "Process chapter 15 text: {previousOutput}"],
    "89": ["ChatGPTAPI", "Generate stunning images for chapter 15: {previousOutput}"],
    "90": ["MobleysoftMASCOM", "Add chapter 15 and images to the book: {previousOutput}"],
    "91": ["ClaudeAPI", "Write captivating chapter 16: {previousOutput}"],
    "92": ["MobleysoftMASCOM", "Process chapter 16 text: {previousOutput}"],
    "93": ["ChatGPTAPI", "Generate stunning images for chapter 16: {previousOutput}"],
    "94": ["MobleysoftMASCOM", "Add chapter 16 and images to the book: {previousOutput}"],
    "95": ["GeminiAPI", "Generate back matter (acknowledgements, author bio): {previousOutput}"],
    "96": ["MobleysoftMASCOM", "Add back matter to the book: {previousOutput}"],
    "97": ["ChatGPTAPI", "Create a captivating cover image: {previousOutput}"],
    "98": ["MobleysoftMASCOM", "Process cover image: {previousOutput}"],
    "99": ["MobleysoftMASCOM", "Superimpose title, author, and other text onto the cover image: {previousOutput}"]
};
