export const corp2soseMilitary = {
    "1": ["id:SoSE", "type:architecture", "name:MilitaryC2System"],
    "2": ["id:C2System", "type:system", "parent:SoSE", "name:CommandAndControlSystem"],
    "3": ["id:SensorSystem", "type:system", "parent:SoSE", "name:SensorSystem"],
    "4": ["id:WeaponSystem", "type:system", "parent:SoSE", "name:WeaponSystem"],
    "5": ["id:CommSystem", "type:system", "parent:SoSE", "name:CommunicationSystem"],
    "6": ["id:Radar", "type:subsystem", "parent:SensorSystem", "name:RadarSubsystem"],
    "7": ["id:Sonar", "type:subsystem", "parent:SensorSystem", "name:SonarSubsystem"],
    "8": ["id:EW", "type:subsystem", "parent:SensorSystem", "name:ElectronicWarfareSubsystem"],
    "9": ["id:Missile", "type:subsystem", "parent:WeaponSystem", "name:MissileSubsystem"],
    "10": ["id:Artillery", "type:subsystem", "parent:WeaponSystem", "name:ArtillerySubsystem"],
    "11": ["id:Radio", "type:subsystem", "parent:CommSystem", "name:RadioSubsystem"],
    "12": ["id:Satellite", "type:subsystem", "parent:CommSystem", "name:SatelliteSubsystem"],
    "13": ["id:OpCenter", "type:subsystem", "parent:C2System", "name:OperationsCenter"],
    "14": ["id:Planning", "type:subsystem", "parent:C2System", "name:PlanningModule"],
    "15": ["id:RadarAnt", "type:element", "parent:Radar", "name:RadarAntenna"],
    "16": ["id:RadarProc", "type:element", "parent:Radar", "name:RadarProcessor"],
    "17": ["id:MissileLauncher", "type:element", "parent:Missile", "name:MissileLauncher"],
    "18": ["id:RadioTransmitter", "type:element", "parent:Radio", "name:RadioTransmitter"],
    "19": ["id:OpDisplay", "type:element", "parent:OpCenter", "name:OperationalDisplay"],
    "20": ["id:IntC2Sensor", "type:interface", "source:C2System", "target:SensorSystem", "name:SensorData"],
    "21": ["id:IntC2Weapon", "type:interface", "source:C2System", "target:WeaponSystem", "name:FireControl"],
    "22": ["id:IntSensorC2", "type:interface", "source:SensorSystem", "target:C2System", "name:SituationalAwareness"],
    "23": ["id:IntCommC2", "type:interface", "source:CommSystem", "target:C2System", "name:CommunicationLink"],
    "24": ["id:IntRadarProc", "type:interface", "source:RadarAnt", "target:RadarProc", "name:SignalProcessing"],
    "25": ["id:ReqRealTime", "type:requirement", "source:SoSE", "target:C2System", "name:RealTimeProcessing"],
    "26": ["id:ReqCyberSec", "type:requirement", "source:SoSE", "target:CommSystem", "name:Cybersecurity"],
    "27": ["id:ReqRange", "type:requirement", "source:SoSE", "target:Radar", "name:DetectionRange500km"],
    "28": ["id:ReqAccuracy", "type:requirement", "source:SoSE", "target:Missile", "name:AccuracyCEP5m"],
    "29": ["id:BehTargetAcq", "type:behavior", "sources:SensorSystem,C2System", "name:TargetAcquisition"],
    "30": ["id:BehThreatEval", "type:behavior", "sources:C2System,SensorSystem", "name:ThreatEvaluation"],
    "31": ["id:BehDecisionMaking", "type:behavior", "sources:C2System,Planning", "name:DecisionMaking"],
    "32": ["id:BehTargetEng", "type:behavior", "sources:WeaponSystem,C2System", "name:TargetEngagement"],
    "33": ["id:BehComm", "type:behavior", "sources:CommSystem", "name:Communication"],
    "34": ["id:EnvElectromagnetic", "type:environment", "target:SoSE", "name:ElectromagneticInterference"],
    "35": ["id:EnvWeather", "type:environment", "target:SensorSystem", "name:WeatherConditions"]
};

export const corp2soseBusiness = {
    "1": ["id:SoSE", "type:architecture", "name:GenericBusiness"],
    "2": ["id:Management", "type:system", "parent:SoSE", "name:Management"],
    "3": ["id:Operations", "type:system", "parent:SoSE", "name:Operations"],
    "4": ["id:HR", "type:system", "parent:SoSE", "name:Human Resources"],
    "5": ["id:Finance", "type:system", "parent:SoSE", "name:Finance"],
    "6": ["id:Marketing", "type:system", "parent:SoSE", "name:Marketing"]
};