name: Matrix Kernel

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  optimize-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y jq
          npm install openai axios fs

      - name: Run Matrix Fixer
        run: node .github/scripts/matrixFixer.js

      - name: Run Matrix Auto-Healer
        run: node .github/scripts/matrixAutoHeal.js

      - name: Run Execution Optimizer
        run: node .github/scripts/matrixExecutionOptimizer.js

      - name: Commit & Push Optimization Logs
        run: |
          git add .matrix/executions/optimization_history.json
          git commit -m "Updated optimization history"
          git push

      - name: Log Completion
        run: echo "Matrix Kernel has successfully healed and optimized execution."
