name: Update Site Directory

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  update-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate site directory
        run: |
          node generate-directory.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add site-directory.json
          git commit -m "Auto-update site directory"
          git push
